create table if not exists public.billing_access (
  id bigint generated by default as identity primary key,
  email text not null unique,
  plan text not null default 'free' check (plan in ('free', 'starter', 'pro')),
  status text not null default 'inactive' check (status in ('inactive', 'pending', 'active', 'cancelled')),
  provider text not null default 'kiwify',
  unlocked_features jsonb not null default '[]'::jsonb,
  last_event jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_billing_access_updated_at on public.billing_access;
create trigger trg_billing_access_updated_at
before update on public.billing_access
for each row
execute function public.set_updated_at();

alter table public.billing_access enable row level security;

-- Permite o app ler apenas a propria linha (auth.email == billing_access.email)
drop policy if exists "read_own_billing_access" on public.billing_access;
create policy "read_own_billing_access"
on public.billing_access
for select
to authenticated
using (auth.jwt() ->> 'email' = email);
