create table if not exists public.support_requests (
  id bigint generated by default as identity primary key,
  email text not null,
  message text not null check (char_length(message) <= 500),
  status text not null default 'new' check (status in ('new', 'answered')),
  source_page text not null default 'unknown',
  created_at timestamptz not null default now(),
  replied_at timestamptz
);

create index if not exists idx_support_requests_created_at
  on public.support_requests (created_at desc);

alter table public.support_requests enable row level security;

-- Sem policies publicas: apenas service role acessa via API server-side.
